[options]
Architecture = auto
SigLevel = Optional TrustAll

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist


[custom]
SigLevel = Optional TrustAll
Server = file://{{PWD}}/custom_repo
